include: package:flame_lint/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    directives_ordering: false
    flutter_style_todos: false
    sort_pub_dependencies: false
