name: Build and deploy Web app

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4

      - name: 'Setup flutter'
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
      
      - name: 'Install dependencies'
        working-directory: ./chicken_invaders
        run: flutter pub get

      - name: 'Build for Web'
        working-directory: ./chicken_invaders
        run: flutter build web --release

      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: build/web
  
  release:
    name: Deploy to GitHub Pages
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Download Build Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: website

      - name: 'Configure GitHub Pages'
        id: pages
        uses: actions/configure-pages@v5
      
      - name: 'Upload GitHub Pages artifact'
        uses: actions/upload-pages-artifact@v3

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
          
