name: Build and deploy Web app

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4

      - name: 'Setup flutter'
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable

      - name: 'Install dependencies'
        working-directory: ./chicken_invaders
        run: flutter pub get

      - name: 'Display GitHub Context'
        run: echo ${{ toJson(github) }}

      - name: 'Build for Web'
        working-directory: ./chicken_invaders
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: flutter build web --release --base-href /$REPOSITORY_NAME/

      - name: 'Create artifact directory'
        working-directory: ./chicken_invaders/build
        run: mkdir -p artifact/_site

      - name: 'Copy build to artifact directory'
        working-directory: ./chicken_invaders/build
        run: mv -v web/* artifact/_site

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./chicken_invaders/build/artifact

  release:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifacts'
        uses: actions/download-artifact@v4
        with:
          name: website

      - name: 'Configure GitHub Pages'
        id: pages
        uses: actions/configure-pages@v5

      - name: 'Upload GitHub Pages artifact'
        uses: actions/upload-pages-artifact@v3

      - name: 'Deploy artifact'
        id: deployment
        uses: actions/deploy-pages@v4
